# Generated by Django 3.2.9 on 2021-12-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, verbose_name='Ссылка на прокси-сервер')),
                ('enabled', models.BooleanField(blank=True, default=True, verbose_name='Включён')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('is_checked', models.BooleanField(blank=True, default=True, verbose_name='Проверена')),
            ],
            options={
                'ordering': ['url'],
                'verbose_name': 'Прокси',
                'verbose_name_plural': 'Прокси',
            },
        ),
    ]
